### ISSUE TITLE
Update User and Token Tests

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#6]
Currently they are @Ignored

Please update them with the new version from your branch and integrate the EntityManager.

**Comment by ArneBinder** [comment]
Done.

**Comment by jnehring** [comment]
Something is still wrong with TokenRepositoryTest. See this text
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.095 sec <<< FAILURE! - in eu.freme.common.persistence.TokenRepositoryTest
testTokenRepository(eu.freme.common.persistence.TokenRepositoryTest)  Time elapsed: 0.06 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at eu.freme.common.persistence.TokenRepositoryTest.testTokenRepository(TokenRepositoryTest.java:85)
```

From this build of FREME common: http://rv1443.1blu.de:8082/job/FREMECommon/63/console

**Comment by ArneBinder** [comment]
I don't know, what's going wrong on jenkins, but I can not reproduce this error at my local machine. @jnehring Is there any way, that more than the one user created in the TokenRepositoryTest is in the database used for testing on jenkins? The test fails, because there are 3 users (after deletion of one token of the one created user) instead of the assumed one... We could do a workaround and save the count of users when the test starts and check at the position, which fails currently, if there are exactly one more than at the beginning.

**Comment by jnehring** [comment]
I will take a look at this.

**Comment by jnehring** [comment]
Done. @ArneBinder please check if the same problem can occur in UserRepositoryTest, then close issue.

**Comment by ArneBinder** [comment]
Checked and added deletion of generated users.
